//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xRoad.Module.BusinessObjects.RoadDataModel
{

    [Persistent(@"EV_LimiteVelocità")]
    public partial class LimiteVelocità : EventoLineare
    {
        int fLimite;
        [DevExpress.Xpo.DisplayName(@"Limite di velocità (km/h)")]
        public int Limite
        {
            get { return fLimite; }
            set { SetPropertyValue<int>(nameof(Limite), ref fLimite, value); }
        }
        Strada fStrada;
        [Association(@"LimiteVelocitàReferencesStrada"), NoForeignKey]
        public Strada Strada
        {
            get { return fStrada; }
            set { SetPropertyValue<Strada>(nameof(Strada), ref fStrada, value); }
        }
    }

}
