//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xMap.Module.BusinessObjects.DataModel
{

    [OptimisticLocking(false)]
    [DeferredDeletion(false)]
    [Persistent(@"OWNER")]
    [DevExpress.Persistent.Base.DefaultClassOptions]
    public partial class Owner : XPObject
    {
        string fCodice;
        [Persistent(@"CODICE")]
        public string Codice
        {
            get { return fCodice; }
            set { SetPropertyValue<string>(nameof(Codice), ref fCodice, value); }
        }
        [Association(@"ParcelReferencesOwner"), Aggregated]
        public XPCollection<Parcel> Parcels { get { return GetCollection<Parcel>(nameof(Parcels)); } }
    }

}
