//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xRoad.Module.Module.BusinessObjects.RoadDataModel
{

    public partial class Arco : xMap.Persistent.BaseImpl.XPSTGeometry
    {
        Percorso fPercorso;
        public Percorso Percorso
        {
            get { return fPercorso; }
            set { SetPropertyValue<Percorso>(nameof(Percorso), ref fPercorso, value); }
        }
        TipoElementoStradale fTipoElementoStradale;
        public TipoElementoStradale TipoElementoStradale
        {
            get { return fTipoElementoStradale; }
            set { SetPropertyValue<TipoElementoStradale>(nameof(TipoElementoStradale), ref fTipoElementoStradale, value); }
        }
        TipoConfineAmministrativo fConfineAmministrativo;
        public TipoConfineAmministrativo ConfineAmministrativo
        {
            get { return fConfineAmministrativo; }
            set { SetPropertyValue<TipoConfineAmministrativo>(nameof(ConfineAmministrativo), ref fConfineAmministrativo, value); }
        }
        TipoCarreggiata fTipoCarreggiata;
        public TipoCarreggiata TipoCarreggiata
        {
            get { return fTipoCarreggiata; }
            set { SetPropertyValue<TipoCarreggiata>(nameof(TipoCarreggiata), ref fTipoCarreggiata, value); }
        }
        double fLunghezza;
        public double Lunghezza
        {
            get { return fLunghezza; }
            set { SetPropertyValue<double>(nameof(Lunghezza), ref fLunghezza, value); }
        }
        TipoStato fStato;
        public TipoStato Stato
        {
            get { return fStato; }
            set { SetPropertyValue<TipoStato>(nameof(Stato), ref fStato, value); }
        }
        TipoFonte fFonte;
        public TipoFonte Fonte
        {
            get { return fFonte; }
            set { SetPropertyValue<TipoFonte>(nameof(Fonte), ref fFonte, value); }
        }
        string fLivelloGrafo;
        public string LivelloGrafo
        {
            get { return fLivelloGrafo; }
            set { SetPropertyValue<string>(nameof(LivelloGrafo), ref fLivelloGrafo, value); }
        }
        string fStatoGrafo;
        public string StatoGrafo
        {
            get { return fStatoGrafo; }
            set { SetPropertyValue<string>(nameof(StatoGrafo), ref fStatoGrafo, value); }
        }
    }

}
