//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xRoad.Module.BusinessObjects.RoadDataModel
{

    [Persistent(@"CENTROABITATO")]
    [DevExpress.Persistent.Base.DefaultClassOptions]
    public partial class CentroAbitato : Evento
    {
        string fNome;
        public string Nome
        {
            get { return fNome; }
            set { SetPropertyValue<string>(nameof(Nome), ref fNome, value); }
        }
        string fCodiceIstat;
        public string CodiceIstat
        {
            get { return fCodiceIstat; }
            set { SetPropertyValue<string>(nameof(CodiceIstat), ref fCodiceIstat, value); }
        }
    }

}
