//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xRoad.Module.Module.BusinessObjects.RoadDataModel
{

    public partial class Cippo : xMap.Persistent.BaseImpl.XPSTGeometry
    {
        Percorso fPercorso;
        public Percorso Percorso
        {
            get { return fPercorso; }
            set { SetPropertyValue<Percorso>(nameof(Percorso), ref fPercorso, value); }
        }
        double fMisura;
        public double Misura
        {
            get { return fMisura; }
            set { SetPropertyValue<double>(nameof(Misura), ref fMisura, value); }
        }
        TipoCippo fTipoCippo;
        public TipoCippo TipoCippo
        {
            get { return fTipoCippo; }
            set { SetPropertyValue<TipoCippo>(nameof(TipoCippo), ref fTipoCippo, value); }
        }
    }

}
