//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xRoad.Module.BusinessObjects.RoadDataModel
{

    [Persistent(@"CIPPO")]
    public partial class Cippo : xMap.Persistent.BaseImpl.XPSTGeometry
    {
        Strada fStrada;
        [Association(@"CippoReferencesStrada"), NoForeignKey]
        public Strada Strada
        {
            get { return fStrada; }
            set { SetPropertyValue<Strada>(nameof(Strada), ref fStrada, value); }
        }
        double fMisura;
        public double Misura
        {
            get { return fMisura; }
            set { SetPropertyValue<double>(nameof(Misura), ref fMisura, value); }
        }
        TipoCippo fTipoCippo;
        public TipoCippo TipoCippo
        {
            get { return fTipoCippo; }
            set { SetPropertyValue<TipoCippo>(nameof(TipoCippo), ref fTipoCippo, value); }
        }
        double fZPos;
        [Persistent(@"Z")]
        public double ZPos
        {
            get { return fZPos; }
            set { SetPropertyValue<double>(nameof(ZPos), ref fZPos, value); }
        }
    }

}
