//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xRoad.Module.BusinessObjects.RoadDataModel
{

    [NonPersistent]
    public partial class EventoLineare : Evento
    {
        double fXPosFinale;
        public double XPosFinale
        {
            get { return fXPosFinale; }
            set { SetPropertyValue<double>(nameof(XPosFinale), ref fXPosFinale, value); }
        }
        double fYPosFinale;
        public double YPosFinale
        {
            get { return fYPosFinale; }
            set { SetPropertyValue<double>(nameof(YPosFinale), ref fYPosFinale, value); }
        }
        double fZPosFinale;
        public double ZPosFinale
        {
            get { return fZPosFinale; }
            set { SetPropertyValue<double>(nameof(ZPosFinale), ref fZPosFinale, value); }
        }
        double fMPosFinale;
        public double MPosFinale
        {
            get { return fMPosFinale; }
            set { SetPropertyValue<double>(nameof(MPosFinale), ref fMPosFinale, value); }
        }
    }

}
