//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xRoad.Module.BusinessObjects.RoadDataModel
{

    [NonPersistent]
    public partial class Evento : xMap.Persistent.Base.DefaultXPObject
    {
        DateTime? fDataInizio;
        public DateTime? DataInizio
        {
            get { return fDataInizio; }
            set { SetPropertyValue<DateTime?>(nameof(DataInizio), ref fDataInizio, value); }
        }
        DateTime? fDataFine;
        public DateTime? DataFine
        {
            get { return fDataFine; }
            set { SetPropertyValue<DateTime?>(nameof(DataFine), ref fDataFine, value); }
        }
        Atto fAtto;
        [Aggregated]
        public Atto Atto
        {
            get { return fAtto; }
            set { SetPropertyValue<Atto>(nameof(Atto), ref fAtto, value); }
        }
        TipoLocalizzazione fTipoLocalizzazione;
        public TipoLocalizzazione TipoLocalizzazione
        {
            get { return fTipoLocalizzazione; }
            set { SetPropertyValue<TipoLocalizzazione>(nameof(TipoLocalizzazione), ref fTipoLocalizzazione, value); }
        }
        TipoCoordinata fTipoCoordinata;
        public TipoCoordinata TipoCoordinata
        {
            get { return fTipoCoordinata; }
            set { SetPropertyValue<TipoCoordinata>(nameof(TipoCoordinata), ref fTipoCoordinata, value); }
        }
        double fXPos;
        public double XPos
        {
            get { return fXPos; }
            set { SetPropertyValue<double>(nameof(XPos), ref fXPos, value); }
        }
        double fYPos;
        public double YPos
        {
            get { return fYPos; }
            set { SetPropertyValue<double>(nameof(YPos), ref fYPos, value); }
        }
        double fZPos;
        public double ZPos
        {
            get { return fZPos; }
            set { SetPropertyValue<double>(nameof(ZPos), ref fZPos, value); }
        }
        double fMPos;
        public double MPos
        {
            get { return fMPos; }
            set { SetPropertyValue<double>(nameof(MPos), ref fMPos, value); }
        }
        TipoGeometriaEvento fTipoGeometria;
        public TipoGeometriaEvento TipoGeometria
        {
            get { return fTipoGeometria; }
            set { SetPropertyValue<TipoGeometriaEvento>(nameof(TipoGeometria), ref fTipoGeometria, value); }
        }
    }

}
