//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xRoad.Module.Module.BusinessObjects.RoadDataModel
{

    [NonPersistent]
    public partial class Evento : XPObject
    {
        string fNome;
        public string Nome
        {
            get { return fNome; }
            set { SetPropertyValue<string>(nameof(Nome), ref fNome, value); }
        }
        Percorso fPercorso;
        public Percorso Percorso
        {
            get { return fPercorso; }
            set { SetPropertyValue<Percorso>(nameof(Percorso), ref fPercorso, value); }
        }
        double fFrom_M;
        public double From_M
        {
            get { return fFrom_M; }
            set { SetPropertyValue<double>(nameof(From_M), ref fFrom_M, value); }
        }
        double fTo_M;
        public double To_M
        {
            get { return fTo_M; }
            set { SetPropertyValue<double>(nameof(To_M), ref fTo_M, value); }
        }
        TipoEvento fTipo;
        public TipoEvento Tipo
        {
            get { return fTipo; }
            set { SetPropertyValue<TipoEvento>(nameof(Tipo), ref fTipo, value); }
        }
    }

}
