//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xRoad.Module.BusinessObjects.RoadDataModel
{

    [Persistent(@"PONTE")]
    public partial class Ponte : EventoLineare
    {
        string fNome;
        public string Nome
        {
            get { return fNome; }
            set { SetPropertyValue<string>(nameof(Nome), ref fNome, value); }
        }
        string fTipoOpera;
        [NoForeignKey]
        public string TipoOpera
        {
            get { return fTipoOpera; }
            set { SetPropertyValue<string>(nameof(TipoOpera), ref fTipoOpera, value); }
        }
        TipoMateriale fTipoImpalcato;
        [NoForeignKey]
        public TipoMateriale TipoImpalcato
        {
            get { return fTipoImpalcato; }
            set { SetPropertyValue<TipoMateriale>(nameof(TipoImpalcato), ref fTipoImpalcato, value); }
        }
        TipoMateriale fTipoSpalla;
        [NoForeignKey]
        public TipoMateriale TipoSpalla
        {
            get { return fTipoSpalla; }
            set { SetPropertyValue<TipoMateriale>(nameof(TipoSpalla), ref fTipoSpalla, value); }
        }
        TipoMateriale fTipoPila;
        [NoForeignKey]
        public TipoMateriale TipoPila
        {
            get { return fTipoPila; }
            set { SetPropertyValue<TipoMateriale>(nameof(TipoPila), ref fTipoPila, value); }
        }
        int fNumeroCampate;
        public int NumeroCampate
        {
            get { return fNumeroCampate; }
            set { SetPropertyValue<int>(nameof(NumeroCampate), ref fNumeroCampate, value); }
        }
        double fLunghezza;
        public double Lunghezza
        {
            get { return fLunghezza; }
            set { SetPropertyValue<double>(nameof(Lunghezza), ref fLunghezza, value); }
        }
        double fLarghezza;
        public double Larghezza
        {
            get { return fLarghezza; }
            set { SetPropertyValue<double>(nameof(Larghezza), ref fLarghezza, value); }
        }
        double fLunghMaxCampata;
        public double LunghMaxCampata
        {
            get { return fLunghMaxCampata; }
            set { SetPropertyValue<double>(nameof(LunghMaxCampata), ref fLunghMaxCampata, value); }
        }
        bool fIlluminazione;
        public bool Illuminazione
        {
            get { return fIlluminazione; }
            set { SetPropertyValue<bool>(nameof(Illuminazione), ref fIlluminazione, value); }
        }
        TipoElementoAttraversato fTipoElementoAttraversato;
        [NoForeignKey]
        public TipoElementoAttraversato TipoElementoAttraversato
        {
            get { return fTipoElementoAttraversato; }
            set { SetPropertyValue<TipoElementoAttraversato>(nameof(TipoElementoAttraversato), ref fTipoElementoAttraversato, value); }
        }
        string fNote;
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>(nameof(Note), ref fNote, value); }
        }
        StatoManutenzione fStatoManutenzione;
        public StatoManutenzione StatoManutenzione
        {
            get { return fStatoManutenzione; }
            set { SetPropertyValue<StatoManutenzione>(nameof(StatoManutenzione), ref fStatoManutenzione, value); }
        }
        string fCodiceARS;
        public string CodiceARS
        {
            get { return fCodiceARS; }
            set { SetPropertyValue<string>(nameof(CodiceARS), ref fCodiceARS, value); }
        }
        double fPortata;
        public double Portata
        {
            get { return fPortata; }
            set { SetPropertyValue<double>(nameof(Portata), ref fPortata, value); }
        }
        Atto fOrdinanzaLimitePeso;
        [Aggregated]
        public Atto OrdinanzaLimitePeso
        {
            get { return fOrdinanzaLimitePeso; }
            set { SetPropertyValue<Atto>(nameof(OrdinanzaLimitePeso), ref fOrdinanzaLimitePeso, value); }
        }
        double fLimitePeso;
        public double LimitePeso
        {
            get { return fLimitePeso; }
            set { SetPropertyValue<double>(nameof(LimitePeso), ref fLimitePeso, value); }
        }
        Strada fStrada;
        [Association(@"PonteReferencesStrada"), NoForeignKey]
        public Strada Strada
        {
            get { return fStrada; }
            set { SetPropertyValue<Strada>(nameof(Strada), ref fStrada, value); }
        }
        [Association(@"IspezioniReferencesPonte"), Aggregated]
        public XPCollection<Ispezione> Ispezioni { get { return GetCollection<Ispezione>(nameof(Ispezioni)); } }
    }

}
