//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xRoad.Module.BusinessObjects.RoadDataModel
{

    public partial class PosizioneSpaziale : xMap.Persistent.Base.DefaultXPObject
    {
        double fXPos;
        public double XPos
        {
            get { return fXPos; }
            set { SetPropertyValue<double>(nameof(XPos), ref fXPos, value); }
        }
        double fYPos;
        public double YPos
        {
            get { return fYPos; }
            set { SetPropertyValue<double>(nameof(YPos), ref fYPos, value); }
        }
        double fZPos;
        public double ZPos
        {
            get { return fZPos; }
            set { SetPropertyValue<double>(nameof(ZPos), ref fZPos, value); }
        }
        double fLatitudine;
        public double Latitudine
        {
            get { return fLatitudine; }
            set { SetPropertyValue<double>(nameof(Latitudine), ref fLatitudine, value); }
        }
        double fLongitudine;
        public double Longitudine
        {
            get { return fLongitudine; }
            set { SetPropertyValue<double>(nameof(Longitudine), ref fLongitudine, value); }
        }
        TipoCoordinata fTipoCoordinata;
        public TipoCoordinata TipoCoordinata
        {
            get { return fTipoCoordinata; }
            set { SetPropertyValue<TipoCoordinata>(nameof(TipoCoordinata), ref fTipoCoordinata, value); }
        }
    }

}
